appName: spring-boot-vuejs

BackendApi:
  image: backend-api
  tag: latest
  replicas: 1
  service:
    port: 8002
    type: ClusterIP
  environment: dev

VueClient:
  image: latest
  replicas: 1
  service:
    port: 8080
    type: ClusterIP
  ingress:
    enabled: true
    host: localhost